global:
  imageRegistry: ""
  imagePullSecrets: []

app:
  enabled: true
  image:
    repository: 10.0.10.156:30002/hexactf/challenge-api
    tag: "latest"
    pullPolicy: Always
  config:
    flaskEnv: development
    secretKey: your-super-secret-key-here
    kafka:
      topic: challenge-status
      groupId: challenge-consumer-group
    db:
      poolSize: 5
      maxOverflow: 10
    loki:
      enabled: true
      protocol: http
      host: plg-loki
      port: 3100
      path: /loki/api/v1/push
      logLevel: info
      app_name: challenge-api
      environment: development      
  kubeconfig:
    enabled: true
    mountPath: /root/.kube
  service:
    type: NodePort
    port: 5001
  


kafka:
  service:
    internal:
      port: 9092
    external:
      port: 9093

mariadb:
  service:
    port: 3306
  auth:
    database: challenge_db
    username: challenge_user
    password: challenge_password