apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka-ui
  labels:
    app: kafka-ui
spec:
  type: NodePort
  ports:
    - port: {{ .Values.kafkaUI.service.port }}
      targetPort: {{ .Values.kafkaUI.service.port }}
      nodePort: {{ .Values.kafkaUI.service.nodePort | default 30007 }}
      protocol: TCP
  selector:
    app: kafka-ui