apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: {{ .Values.zookeeper.image.repository }}:{{ .Values.zookeeper.image.tag }}
          ports:
            - containerPort: {{ .Values.zookeeper.service.port }}
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: {{ .Values.zookeeper.config.clientPort | quote }}
            - name: ZOOKEEPER_TICK_TIME
              value: {{ .Values.zookeeper.config.tickTime | quote }}