apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-zookeeper
spec:
  ports:
    - port: {{ .Values.zookeeper.service.port }}
      targetPort: {{ .Values.zookeeper.service.port }}
  selector:
    app: zookeeper