apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: hexactf
data:
  my.cnf: |
    [mysqld]
    bind-address = 0.0.0.0
    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci
    log-error = /var/log/mysql/error.log
    slow-query-log = 1
    slow-query-log-file = /var/log/mysql/slow.log
    long_query_time = 2
    general_log = 1
    general_log_file = /var/log/mysql/general.log
    wait_timeout = 28800
    interactive_timeout = 28800
