apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mariadb
spec:
  ports:
    - name: mariadb
      port: {{ .Values.mariadb.service.port }}
      targetPort: {{ .Values.mariadb.service.port }}
    - name: metrics
      port: 9104
      targetPort: 9104
      protocol: TCP
  selector:
    app: mariadb