apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mariadb
  namespace: hexactf
  labels:
    app: mariadb
spec:
  selector:
    app: mariadb
  ports:
    - name: mariadb-port
      port: {{ .Values.mariadb.service.port }}
      targetPort: {{ .Values.mariadb.service.port }}
    - name: metrics
      port: 9104
      targetPort: 9104
