apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-exporter-config
data:
  .my.cnf: |
    [client]
    user=exporter
    password=password
    host=hexactf-helm-mariadb.hexactf.svc.cluster.local
    port=3306
