apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysqld-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqld-exporter
  template:
    metadata:
      labels:
        app: mysqld-exporter
    spec:
      containers:
        - name: mysqld-exporter
          image: prom/mysqld-exporter:latest
          ports:
            - containerPort: 9104
          env:
            - name: DATA_SOURCE_NAME
              value: "exporter:exporter-password@({{ .Release.Name }}-mariadb:3306)/"
          volumeMounts:
            - name: mysqld-exporter-config
              mountPath: /etc/mysql/conf.d
      volumes:
        - name: mysqld-exporter-config
          configMap:
            name: mysqld-exporter-config
