apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mariadb-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mariadb
  namespaceSelector:
    matchNames:
      - hexactf
  endpoints:
    - interval: 30s
      port: 9104
