# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: {{ .Release.Name }}-mariadb-monitor
#   namespace: monitoring
#   labels:
#     release: prometheus
# spec:
#   selector:
#     matchLabels:
#       app: mariadb
#   namespaceSelector:
#     matchNames:
#       - {{ .Release.Namespace }}
#   endpoints:
#     - port: mariadb-metrics
#       interval: 30s
#       scrapeTimeout: 10s
#       path: /metrics
#       scheme: http
