apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mariadb-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mariadb
  namespaceSelector:
    matchNames:
      - hexactf
  endpoints:
    - honorLabels: true
      path: /metrics
      port: metrics
      scheme: http
      interval: 15s
