apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-mariadb-metrics
  labels:
    app: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
