apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hexactf-mysqld-exporter
  namespace: monitoring # Prometheus가 있는 네임스페이스에 생성
  labels:
    release: prometheus # Prometheus Operator가 찾을 수 있도록 설정
spec:
  selector:
    matchLabels:
      app: mysqld-exporter # hexactf ns의 mysqld-exporter 서비스 선택
  namespaceSelector:
    matchNames:
      - hexactf # 다른 네임스페이스를 감시할 수 있도록 설정
  endpoints:
    - port: mysqld-exporter-metrics
      interval: 30s
      scrapeTimeout: 10s
      path: /metrics
