apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mariadb-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mariadb
  namespaceSelector:
    matchNames:
      - hexactf
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
