global:
  imageRegistry: ""
  imagePullSecrets: []

mariadb:
  enabled: true
  image: 
    
    repository: 10.0.10.156:30002/hexactf/hexactf-db
    tag: "1.16.0"
    pullPolicy: Always
  service:
    port: 3306
  auth:
    rootPassword: root_password
    database: CTF
    username: user
    password: password
  persistence:
    enabled: true
    storageClass: "nfs-client"
    size: 8Gi
  config:
    characterSet: utf8mb4
    collation: utf8mb4_unicode_ci
