global:
  imageRegistry: ""
  imagePullSecrets: []

mariadb:
  enabled: true
  image: 
    repository: 10.0.10.156:30002/hexactf/hexactf-db
    tag: "1.16.0"
    pullPolicy: IfNotPresent
  service:
    port: 3306
  auth:
    rootPassword: root_password
    database: challenge_db
    username: challenge_user
    password: challenge_password
  persistence:
    enabled: true
    storageClass: "nfs-client"
    size: 8Gi
  config:
    characterSet: utf8mb4
    collation: utf8mb4_unicode_ci

mysqldExporter:
  enabled: true
  image:
    repository: prom/mysqld-exporter
    tag: v0.16.0
  service:
    port: 9104
  config:
    user: exporter
    password: exporter_password
    host: 127.0.0.1
    port: 3306