apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ctf-app
spec:
  type: NodePort
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.port }}
      protocol: TCP
      name: http-ctf-app
      nodePort: {{ .Values.app.service.nodePort | default 30001 }}
  selector:
    app: ctf-app
