global:
  imageRegistry: ""
  imagePullSecrets: []

operator:
  enabled: true
  image:
    repository: 10.0.10.156:30002/hexactf/challenge-operator
    tag: "latest"
    pullPolicy: Always
  config:
    development: true
    metricsAddr: ":8081"
    logLevel: "debug"
  kubeconfig:
    enabled: true
    mountPath: /home/ubuntu/.kube/config

kafka:
  service:
    internal: 
      port: 9092
    external:
      port: 9093

loki:
  host: http://loki.monitoring.svc.cluster.local:3100